[[redirects]]
from = "https://handbook.tmat.me/en/*"
to = "https://papercraft.tmat.me/book/:splat"
force = true
status = 301

[[redirects]]
from = "https://handbook.tmat.me/ru/*"
to = "https://papercraft.tmat.me/ru/book/:splat"
force = true
status = 301

[[redirects]]
from = "https://handbook.tmat.me/"
to = "https://papercraft.tmat.me/"
force = true
status = 301

[[redirects]]
from = "/book/*"
to = "/ru/book/:splat"
force = true
status = 302
conditions = { Language = ["ru"] }
